apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: spring-sensors
  labels:
    app.kubernetes.io/part-of: spring-sensors
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
spec:
  source:
    image: 233028603830.dkr.ecr.us-east-1.amazonaws.com/tap-supply-chain-1-4/spring-sensors-dev-workspace-bundle:e63e2c6d-7283-414b-8e6b-370b0abd3346
